#if !canImport(ObjectiveC)
   import XCTest

   extension BuzzBLETests {
      // DO NOT MODIFY: This is autogenerated, use:
      //   `swift test --generate-linuxmain`
      // to regenerate.
      static let __allTests__BuzzBLETests = [
         ("testAuthorize", testAuthorize),
         ("testBatteryInfo", testBatteryInfo),
         ("testClearMotorsQueue", testClearMotorsQueue),
         ("testConnectDisconnectSuccess", testConnectDisconnectSuccess),
         ("testDeviceDisappearanceSuccess", testDeviceDisappearanceSuccess),
         ("testDeviceInfo", testDeviceInfo),
         ("testEnableDisableMic", testEnableDisableMic),
         ("testEnableDisableMotors", testEnableDisableMotors),
         ("testLinuxTestSuiteIncludesAllTests", testLinuxTestSuiteIncludesAllTests),
         ("testUnknownCommand", testUnknownCommand),
      ]
   }

   public func __allTests() -> [XCTestCaseEntry] {
      return [
         testCase(BuzzBLETests.__allTests__BuzzBLETests),
      ]
   }
#endif
